// This file is part of CycloneDX GoMod
//
// Licensed under the Apache License, Version 2.0 (the “License”);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an “AS IS” BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0
// Copyright (c) OWASP Foundation. All Rights Reserved.

// Code generated by go generate. DO NOT EDIT.

// License list version: e0b157f
// Generated at:         2021-07-18T13:21:40+02:00

package spdx

func init() {
	licenses = []License{
		{
			ID:        "0BSD",
			Reference: "https://spdx.org/licenses/0BSD.html",
		},
		{
			ID:        "AAL",
			Reference: "https://spdx.org/licenses/AAL.html",
		},
		{
			ID:        "ADSL",
			Reference: "https://spdx.org/licenses/ADSL.html",
		},
		{
			ID:        "AFL-1.1",
			Reference: "https://spdx.org/licenses/AFL-1.1.html",
		},
		{
			ID:        "AFL-1.2",
			Reference: "https://spdx.org/licenses/AFL-1.2.html",
		},
		{
			ID:        "AFL-2.0",
			Reference: "https://spdx.org/licenses/AFL-2.0.html",
		},
		{
			ID:        "AFL-2.1",
			Reference: "https://spdx.org/licenses/AFL-2.1.html",
		},
		{
			ID:        "AFL-3.0",
			Reference: "https://spdx.org/licenses/AFL-3.0.html",
		},
		{
			ID:        "AGPL-1.0",
			Reference: "https://spdx.org/licenses/AGPL-1.0.html",
		},
		{
			ID:        "AGPL-1.0-only",
			Reference: "https://spdx.org/licenses/AGPL-1.0-only.html",
		},
		{
			ID:        "AGPL-1.0-or-later",
			Reference: "https://spdx.org/licenses/AGPL-1.0-or-later.html",
		},
		{
			ID:        "AGPL-3.0",
			Reference: "https://spdx.org/licenses/AGPL-3.0.html",
		},
		{
			ID:        "AGPL-3.0-only",
			Reference: "https://spdx.org/licenses/AGPL-3.0-only.html",
		},
		{
			ID:        "AGPL-3.0-or-later",
			Reference: "https://spdx.org/licenses/AGPL-3.0-or-later.html",
		},
		{
			ID:        "AMDPLPA",
			Reference: "https://spdx.org/licenses/AMDPLPA.html",
		},
		{
			ID:        "AML",
			Reference: "https://spdx.org/licenses/AML.html",
		},
		{
			ID:        "AMPAS",
			Reference: "https://spdx.org/licenses/AMPAS.html",
		},
		{
			ID:        "ANTLR-PD",
			Reference: "https://spdx.org/licenses/ANTLR-PD.html",
		},
		{
			ID:        "ANTLR-PD-fallback",
			Reference: "https://spdx.org/licenses/ANTLR-PD-fallback.html",
		},
		{
			ID:        "APAFML",
			Reference: "https://spdx.org/licenses/APAFML.html",
		},
		{
			ID:        "APL-1.0",
			Reference: "https://spdx.org/licenses/APL-1.0.html",
		},
		{
			ID:        "APSL-1.0",
			Reference: "https://spdx.org/licenses/APSL-1.0.html",
		},
		{
			ID:        "APSL-1.1",
			Reference: "https://spdx.org/licenses/APSL-1.1.html",
		},
		{
			ID:        "APSL-1.2",
			Reference: "https://spdx.org/licenses/APSL-1.2.html",
		},
		{
			ID:        "APSL-2.0",
			Reference: "https://spdx.org/licenses/APSL-2.0.html",
		},
		{
			ID:        "Abstyles",
			Reference: "https://spdx.org/licenses/Abstyles.html",
		},
		{
			ID:        "Adobe-2006",
			Reference: "https://spdx.org/licenses/Adobe-2006.html",
		},
		{
			ID:        "Adobe-Glyph",
			Reference: "https://spdx.org/licenses/Adobe-Glyph.html",
		},
		{
			ID:        "Afmparse",
			Reference: "https://spdx.org/licenses/Afmparse.html",
		},
		{
			ID:        "Aladdin",
			Reference: "https://spdx.org/licenses/Aladdin.html",
		},
		{
			ID:        "Apache-1.0",
			Reference: "https://spdx.org/licenses/Apache-1.0.html",
		},
		{
			ID:        "Apache-1.1",
			Reference: "https://spdx.org/licenses/Apache-1.1.html",
		},
		{
			ID:        "Apache-2.0",
			Reference: "https://spdx.org/licenses/Apache-2.0.html",
		},
		{
			ID:        "Artistic-1.0",
			Reference: "https://spdx.org/licenses/Artistic-1.0.html",
		},
		{
			ID:        "Artistic-1.0-Perl",
			Reference: "https://spdx.org/licenses/Artistic-1.0-Perl.html",
		},
		{
			ID:        "Artistic-1.0-cl8",
			Reference: "https://spdx.org/licenses/Artistic-1.0-cl8.html",
		},
		{
			ID:        "Artistic-2.0",
			Reference: "https://spdx.org/licenses/Artistic-2.0.html",
		},
		{
			ID:        "BSD-1-Clause",
			Reference: "https://spdx.org/licenses/BSD-1-Clause.html",
		},
		{
			ID:        "BSD-2-Clause",
			Reference: "https://spdx.org/licenses/BSD-2-Clause.html",
		},
		{
			ID:        "BSD-2-Clause-FreeBSD",
			Reference: "https://spdx.org/licenses/BSD-2-Clause-FreeBSD.html",
		},
		{
			ID:        "BSD-2-Clause-NetBSD",
			Reference: "https://spdx.org/licenses/BSD-2-Clause-NetBSD.html",
		},
		{
			ID:        "BSD-2-Clause-Patent",
			Reference: "https://spdx.org/licenses/BSD-2-Clause-Patent.html",
		},
		{
			ID:        "BSD-2-Clause-Views",
			Reference: "https://spdx.org/licenses/BSD-2-Clause-Views.html",
		},
		{
			ID:        "BSD-3-Clause",
			Reference: "https://spdx.org/licenses/BSD-3-Clause.html",
		},
		{
			ID:        "BSD-3-Clause-Attribution",
			Reference: "https://spdx.org/licenses/BSD-3-Clause-Attribution.html",
		},
		{
			ID:        "BSD-3-Clause-Clear",
			Reference: "https://spdx.org/licenses/BSD-3-Clause-Clear.html",
		},
		{
			ID:        "BSD-3-Clause-LBNL",
			Reference: "https://spdx.org/licenses/BSD-3-Clause-LBNL.html",
		},
		{
			ID:        "BSD-3-Clause-Modification",
			Reference: "https://spdx.org/licenses/BSD-3-Clause-Modification.html",
		},
		{
			ID:        "BSD-3-Clause-No-Military-License",
			Reference: "https://spdx.org/licenses/BSD-3-Clause-No-Military-License.html",
		},
		{
			ID:        "BSD-3-Clause-No-Nuclear-License",
			Reference: "https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License.html",
		},
		{
			ID:        "BSD-3-Clause-No-Nuclear-License-2014",
			Reference: "https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-License-2014.html",
		},
		{
			ID:        "BSD-3-Clause-No-Nuclear-Warranty",
			Reference: "https://spdx.org/licenses/BSD-3-Clause-No-Nuclear-Warranty.html",
		},
		{
			ID:        "BSD-3-Clause-Open-MPI",
			Reference: "https://spdx.org/licenses/BSD-3-Clause-Open-MPI.html",
		},
		{
			ID:        "BSD-4-Clause",
			Reference: "https://spdx.org/licenses/BSD-4-Clause.html",
		},
		{
			ID:        "BSD-4-Clause-Shortened",
			Reference: "https://spdx.org/licenses/BSD-4-Clause-Shortened.html",
		},
		{
			ID:        "BSD-4-Clause-UC",
			Reference: "https://spdx.org/licenses/BSD-4-Clause-UC.html",
		},
		{
			ID:        "BSD-Protection",
			Reference: "https://spdx.org/licenses/BSD-Protection.html",
		},
		{
			ID:        "BSD-Source-Code",
			Reference: "https://spdx.org/licenses/BSD-Source-Code.html",
		},
		{
			ID:        "BSL-1.0",
			Reference: "https://spdx.org/licenses/BSL-1.0.html",
		},
		{
			ID:        "BUSL-1.1",
			Reference: "https://spdx.org/licenses/BUSL-1.1.html",
		},
		{
			ID:        "Bahyph",
			Reference: "https://spdx.org/licenses/Bahyph.html",
		},
		{
			ID:        "Barr",
			Reference: "https://spdx.org/licenses/Barr.html",
		},
		{
			ID:        "Beerware",
			Reference: "https://spdx.org/licenses/Beerware.html",
		},
		{
			ID:        "BitTorrent-1.0",
			Reference: "https://spdx.org/licenses/BitTorrent-1.0.html",
		},
		{
			ID:        "BitTorrent-1.1",
			Reference: "https://spdx.org/licenses/BitTorrent-1.1.html",
		},
		{
			ID:        "BlueOak-1.0.0",
			Reference: "https://spdx.org/licenses/BlueOak-1.0.0.html",
		},
		{
			ID:        "Borceux",
			Reference: "https://spdx.org/licenses/Borceux.html",
		},
		{
			ID:        "C-UDA-1.0",
			Reference: "https://spdx.org/licenses/C-UDA-1.0.html",
		},
		{
			ID:        "CAL-1.0",
			Reference: "https://spdx.org/licenses/CAL-1.0.html",
		},
		{
			ID:        "CAL-1.0-Combined-Work-Exception",
			Reference: "https://spdx.org/licenses/CAL-1.0-Combined-Work-Exception.html",
		},
		{
			ID:        "CATOSL-1.1",
			Reference: "https://spdx.org/licenses/CATOSL-1.1.html",
		},
		{
			ID:        "CC-BY-1.0",
			Reference: "https://spdx.org/licenses/CC-BY-1.0.html",
		},
		{
			ID:        "CC-BY-2.0",
			Reference: "https://spdx.org/licenses/CC-BY-2.0.html",
		},
		{
			ID:        "CC-BY-2.5",
			Reference: "https://spdx.org/licenses/CC-BY-2.5.html",
		},
		{
			ID:        "CC-BY-2.5-AU",
			Reference: "https://spdx.org/licenses/CC-BY-2.5-AU.html",
		},
		{
			ID:        "CC-BY-3.0",
			Reference: "https://spdx.org/licenses/CC-BY-3.0.html",
		},
		{
			ID:        "CC-BY-3.0-AT",
			Reference: "https://spdx.org/licenses/CC-BY-3.0-AT.html",
		},
		{
			ID:        "CC-BY-3.0-US",
			Reference: "https://spdx.org/licenses/CC-BY-3.0-US.html",
		},
		{
			ID:        "CC-BY-4.0",
			Reference: "https://spdx.org/licenses/CC-BY-4.0.html",
		},
		{
			ID:        "CC-BY-NC-1.0",
			Reference: "https://spdx.org/licenses/CC-BY-NC-1.0.html",
		},
		{
			ID:        "CC-BY-NC-2.0",
			Reference: "https://spdx.org/licenses/CC-BY-NC-2.0.html",
		},
		{
			ID:        "CC-BY-NC-2.5",
			Reference: "https://spdx.org/licenses/CC-BY-NC-2.5.html",
		},
		{
			ID:        "CC-BY-NC-3.0",
			Reference: "https://spdx.org/licenses/CC-BY-NC-3.0.html",
		},
		{
			ID:        "CC-BY-NC-4.0",
			Reference: "https://spdx.org/licenses/CC-BY-NC-4.0.html",
		},
		{
			ID:        "CC-BY-NC-ND-1.0",
			Reference: "https://spdx.org/licenses/CC-BY-NC-ND-1.0.html",
		},
		{
			ID:        "CC-BY-NC-ND-2.0",
			Reference: "https://spdx.org/licenses/CC-BY-NC-ND-2.0.html",
		},
		{
			ID:        "CC-BY-NC-ND-2.5",
			Reference: "https://spdx.org/licenses/CC-BY-NC-ND-2.5.html",
		},
		{
			ID:        "CC-BY-NC-ND-3.0",
			Reference: "https://spdx.org/licenses/CC-BY-NC-ND-3.0.html",
		},
		{
			ID:        "CC-BY-NC-ND-3.0-IGO",
			Reference: "https://spdx.org/licenses/CC-BY-NC-ND-3.0-IGO.html",
		},
		{
			ID:        "CC-BY-NC-ND-4.0",
			Reference: "https://spdx.org/licenses/CC-BY-NC-ND-4.0.html",
		},
		{
			ID:        "CC-BY-NC-SA-1.0",
			Reference: "https://spdx.org/licenses/CC-BY-NC-SA-1.0.html",
		},
		{
			ID:        "CC-BY-NC-SA-2.0",
			Reference: "https://spdx.org/licenses/CC-BY-NC-SA-2.0.html",
		},
		{
			ID:        "CC-BY-NC-SA-2.5",
			Reference: "https://spdx.org/licenses/CC-BY-NC-SA-2.5.html",
		},
		{
			ID:        "CC-BY-NC-SA-3.0",
			Reference: "https://spdx.org/licenses/CC-BY-NC-SA-3.0.html",
		},
		{
			ID:        "CC-BY-NC-SA-4.0",
			Reference: "https://spdx.org/licenses/CC-BY-NC-SA-4.0.html",
		},
		{
			ID:        "CC-BY-ND-1.0",
			Reference: "https://spdx.org/licenses/CC-BY-ND-1.0.html",
		},
		{
			ID:        "CC-BY-ND-2.0",
			Reference: "https://spdx.org/licenses/CC-BY-ND-2.0.html",
		},
		{
			ID:        "CC-BY-ND-2.5",
			Reference: "https://spdx.org/licenses/CC-BY-ND-2.5.html",
		},
		{
			ID:        "CC-BY-ND-3.0",
			Reference: "https://spdx.org/licenses/CC-BY-ND-3.0.html",
		},
		{
			ID:        "CC-BY-ND-4.0",
			Reference: "https://spdx.org/licenses/CC-BY-ND-4.0.html",
		},
		{
			ID:        "CC-BY-SA-1.0",
			Reference: "https://spdx.org/licenses/CC-BY-SA-1.0.html",
		},
		{
			ID:        "CC-BY-SA-2.0",
			Reference: "https://spdx.org/licenses/CC-BY-SA-2.0.html",
		},
		{
			ID:        "CC-BY-SA-2.0-UK",
			Reference: "https://spdx.org/licenses/CC-BY-SA-2.0-UK.html",
		},
		{
			ID:        "CC-BY-SA-2.1-JP",
			Reference: "https://spdx.org/licenses/CC-BY-SA-2.1-JP.html",
		},
		{
			ID:        "CC-BY-SA-2.5",
			Reference: "https://spdx.org/licenses/CC-BY-SA-2.5.html",
		},
		{
			ID:        "CC-BY-SA-3.0",
			Reference: "https://spdx.org/licenses/CC-BY-SA-3.0.html",
		},
		{
			ID:        "CC-BY-SA-3.0-AT",
			Reference: "https://spdx.org/licenses/CC-BY-SA-3.0-AT.html",
		},
		{
			ID:        "CC-BY-SA-4.0",
			Reference: "https://spdx.org/licenses/CC-BY-SA-4.0.html",
		},
		{
			ID:        "CC-PDDC",
			Reference: "https://spdx.org/licenses/CC-PDDC.html",
		},
		{
			ID:        "CC0-1.0",
			Reference: "https://spdx.org/licenses/CC0-1.0.html",
		},
		{
			ID:        "CDDL-1.0",
			Reference: "https://spdx.org/licenses/CDDL-1.0.html",
		},
		{
			ID:        "CDDL-1.1",
			Reference: "https://spdx.org/licenses/CDDL-1.1.html",
		},
		{
			ID:        "CDL-1.0",
			Reference: "https://spdx.org/licenses/CDL-1.0.html",
		},
		{
			ID:        "CDLA-Permissive-1.0",
			Reference: "https://spdx.org/licenses/CDLA-Permissive-1.0.html",
		},
		{
			ID:        "CDLA-Sharing-1.0",
			Reference: "https://spdx.org/licenses/CDLA-Sharing-1.0.html",
		},
		{
			ID:        "CECILL-1.0",
			Reference: "https://spdx.org/licenses/CECILL-1.0.html",
		},
		{
			ID:        "CECILL-1.1",
			Reference: "https://spdx.org/licenses/CECILL-1.1.html",
		},
		{
			ID:        "CECILL-2.0",
			Reference: "https://spdx.org/licenses/CECILL-2.0.html",
		},
		{
			ID:        "CECILL-2.1",
			Reference: "https://spdx.org/licenses/CECILL-2.1.html",
		},
		{
			ID:        "CECILL-B",
			Reference: "https://spdx.org/licenses/CECILL-B.html",
		},
		{
			ID:        "CECILL-C",
			Reference: "https://spdx.org/licenses/CECILL-C.html",
		},
		{
			ID:        "CERN-OHL-1.1",
			Reference: "https://spdx.org/licenses/CERN-OHL-1.1.html",
		},
		{
			ID:        "CERN-OHL-1.2",
			Reference: "https://spdx.org/licenses/CERN-OHL-1.2.html",
		},
		{
			ID:        "CERN-OHL-P-2.0",
			Reference: "https://spdx.org/licenses/CERN-OHL-P-2.0.html",
		},
		{
			ID:        "CERN-OHL-S-2.0",
			Reference: "https://spdx.org/licenses/CERN-OHL-S-2.0.html",
		},
		{
			ID:        "CERN-OHL-W-2.0",
			Reference: "https://spdx.org/licenses/CERN-OHL-W-2.0.html",
		},
		{
			ID:        "CNRI-Jython",
			Reference: "https://spdx.org/licenses/CNRI-Jython.html",
		},
		{
			ID:        "CNRI-Python",
			Reference: "https://spdx.org/licenses/CNRI-Python.html",
		},
		{
			ID:        "CNRI-Python-GPL-Compatible",
			Reference: "https://spdx.org/licenses/CNRI-Python-GPL-Compatible.html",
		},
		{
			ID:        "CPAL-1.0",
			Reference: "https://spdx.org/licenses/CPAL-1.0.html",
		},
		{
			ID:        "CPL-1.0",
			Reference: "https://spdx.org/licenses/CPL-1.0.html",
		},
		{
			ID:        "CPOL-1.02",
			Reference: "https://spdx.org/licenses/CPOL-1.02.html",
		},
		{
			ID:        "CUA-OPL-1.0",
			Reference: "https://spdx.org/licenses/CUA-OPL-1.0.html",
		},
		{
			ID:        "Caldera",
			Reference: "https://spdx.org/licenses/Caldera.html",
		},
		{
			ID:        "ClArtistic",
			Reference: "https://spdx.org/licenses/ClArtistic.html",
		},
		{
			ID:        "Condor-1.1",
			Reference: "https://spdx.org/licenses/Condor-1.1.html",
		},
		{
			ID:        "Crossword",
			Reference: "https://spdx.org/licenses/Crossword.html",
		},
		{
			ID:        "CrystalStacker",
			Reference: "https://spdx.org/licenses/CrystalStacker.html",
		},
		{
			ID:        "Cube",
			Reference: "https://spdx.org/licenses/Cube.html",
		},
		{
			ID:        "D-FSL-1.0",
			Reference: "https://spdx.org/licenses/D-FSL-1.0.html",
		},
		{
			ID:        "DOC",
			Reference: "https://spdx.org/licenses/DOC.html",
		},
		{
			ID:        "DRL-1.0",
			Reference: "https://spdx.org/licenses/DRL-1.0.html",
		},
		{
			ID:        "DSDP",
			Reference: "https://spdx.org/licenses/DSDP.html",
		},
		{
			ID:        "Dotseqn",
			Reference: "https://spdx.org/licenses/Dotseqn.html",
		},
		{
			ID:        "ECL-1.0",
			Reference: "https://spdx.org/licenses/ECL-1.0.html",
		},
		{
			ID:        "ECL-2.0",
			Reference: "https://spdx.org/licenses/ECL-2.0.html",
		},
		{
			ID:        "EFL-1.0",
			Reference: "https://spdx.org/licenses/EFL-1.0.html",
		},
		{
			ID:        "EFL-2.0",
			Reference: "https://spdx.org/licenses/EFL-2.0.html",
		},
		{
			ID:        "EPICS",
			Reference: "https://spdx.org/licenses/EPICS.html",
		},
		{
			ID:        "EPL-1.0",
			Reference: "https://spdx.org/licenses/EPL-1.0.html",
		},
		{
			ID:        "EPL-2.0",
			Reference: "https://spdx.org/licenses/EPL-2.0.html",
		},
		{
			ID:        "EUDatagrid",
			Reference: "https://spdx.org/licenses/EUDatagrid.html",
		},
		{
			ID:        "EUPL-1.0",
			Reference: "https://spdx.org/licenses/EUPL-1.0.html",
		},
		{
			ID:        "EUPL-1.1",
			Reference: "https://spdx.org/licenses/EUPL-1.1.html",
		},
		{
			ID:        "EUPL-1.2",
			Reference: "https://spdx.org/licenses/EUPL-1.2.html",
		},
		{
			ID:        "Entessa",
			Reference: "https://spdx.org/licenses/Entessa.html",
		},
		{
			ID:        "ErlPL-1.1",
			Reference: "https://spdx.org/licenses/ErlPL-1.1.html",
		},
		{
			ID:        "Eurosym",
			Reference: "https://spdx.org/licenses/Eurosym.html",
		},
		{
			ID:        "FSFAP",
			Reference: "https://spdx.org/licenses/FSFAP.html",
		},
		{
			ID:        "FSFUL",
			Reference: "https://spdx.org/licenses/FSFUL.html",
		},
		{
			ID:        "FSFULLR",
			Reference: "https://spdx.org/licenses/FSFULLR.html",
		},
		{
			ID:        "FTL",
			Reference: "https://spdx.org/licenses/FTL.html",
		},
		{
			ID:        "Fair",
			Reference: "https://spdx.org/licenses/Fair.html",
		},
		{
			ID:        "Frameworx-1.0",
			Reference: "https://spdx.org/licenses/Frameworx-1.0.html",
		},
		{
			ID:        "FreeBSD-DOC",
			Reference: "https://spdx.org/licenses/FreeBSD-DOC.html",
		},
		{
			ID:        "FreeImage",
			Reference: "https://spdx.org/licenses/FreeImage.html",
		},
		{
			ID:        "GD",
			Reference: "https://spdx.org/licenses/GD.html",
		},
		{
			ID:        "GFDL-1.1",
			Reference: "https://spdx.org/licenses/GFDL-1.1.html",
		},
		{
			ID:        "GFDL-1.1-invariants-only",
			Reference: "https://spdx.org/licenses/GFDL-1.1-invariants-only.html",
		},
		{
			ID:        "GFDL-1.1-invariants-or-later",
			Reference: "https://spdx.org/licenses/GFDL-1.1-invariants-or-later.html",
		},
		{
			ID:        "GFDL-1.1-no-invariants-only",
			Reference: "https://spdx.org/licenses/GFDL-1.1-no-invariants-only.html",
		},
		{
			ID:        "GFDL-1.1-no-invariants-or-later",
			Reference: "https://spdx.org/licenses/GFDL-1.1-no-invariants-or-later.html",
		},
		{
			ID:        "GFDL-1.1-only",
			Reference: "https://spdx.org/licenses/GFDL-1.1-only.html",
		},
		{
			ID:        "GFDL-1.1-or-later",
			Reference: "https://spdx.org/licenses/GFDL-1.1-or-later.html",
		},
		{
			ID:        "GFDL-1.2",
			Reference: "https://spdx.org/licenses/GFDL-1.2.html",
		},
		{
			ID:        "GFDL-1.2-invariants-only",
			Reference: "https://spdx.org/licenses/GFDL-1.2-invariants-only.html",
		},
		{
			ID:        "GFDL-1.2-invariants-or-later",
			Reference: "https://spdx.org/licenses/GFDL-1.2-invariants-or-later.html",
		},
		{
			ID:        "GFDL-1.2-no-invariants-only",
			Reference: "https://spdx.org/licenses/GFDL-1.2-no-invariants-only.html",
		},
		{
			ID:        "GFDL-1.2-no-invariants-or-later",
			Reference: "https://spdx.org/licenses/GFDL-1.2-no-invariants-or-later.html",
		},
		{
			ID:        "GFDL-1.2-only",
			Reference: "https://spdx.org/licenses/GFDL-1.2-only.html",
		},
		{
			ID:        "GFDL-1.2-or-later",
			Reference: "https://spdx.org/licenses/GFDL-1.2-or-later.html",
		},
		{
			ID:        "GFDL-1.3",
			Reference: "https://spdx.org/licenses/GFDL-1.3.html",
		},
		{
			ID:        "GFDL-1.3-invariants-only",
			Reference: "https://spdx.org/licenses/GFDL-1.3-invariants-only.html",
		},
		{
			ID:        "GFDL-1.3-invariants-or-later",
			Reference: "https://spdx.org/licenses/GFDL-1.3-invariants-or-later.html",
		},
		{
			ID:        "GFDL-1.3-no-invariants-only",
			Reference: "https://spdx.org/licenses/GFDL-1.3-no-invariants-only.html",
		},
		{
			ID:        "GFDL-1.3-no-invariants-or-later",
			Reference: "https://spdx.org/licenses/GFDL-1.3-no-invariants-or-later.html",
		},
		{
			ID:        "GFDL-1.3-only",
			Reference: "https://spdx.org/licenses/GFDL-1.3-only.html",
		},
		{
			ID:        "GFDL-1.3-or-later",
			Reference: "https://spdx.org/licenses/GFDL-1.3-or-later.html",
		},
		{
			ID:        "GL2PS",
			Reference: "https://spdx.org/licenses/GL2PS.html",
		},
		{
			ID:        "GLWTPL",
			Reference: "https://spdx.org/licenses/GLWTPL.html",
		},
		{
			ID:        "GPL-1.0",
			Reference: "https://spdx.org/licenses/GPL-1.0.html",
		},
		{
			ID:        "GPL-1.0+",
			Reference: "https://spdx.org/licenses/GPL-1.0+.html",
		},
		{
			ID:        "GPL-1.0-only",
			Reference: "https://spdx.org/licenses/GPL-1.0-only.html",
		},
		{
			ID:        "GPL-1.0-or-later",
			Reference: "https://spdx.org/licenses/GPL-1.0-or-later.html",
		},
		{
			ID:        "GPL-2.0",
			Reference: "https://spdx.org/licenses/GPL-2.0.html",
		},
		{
			ID:        "GPL-2.0+",
			Reference: "https://spdx.org/licenses/GPL-2.0+.html",
		},
		{
			ID:        "GPL-2.0-only",
			Reference: "https://spdx.org/licenses/GPL-2.0-only.html",
		},
		{
			ID:        "GPL-2.0-or-later",
			Reference: "https://spdx.org/licenses/GPL-2.0-or-later.html",
		},
		{
			ID:        "GPL-2.0-with-GCC-exception",
			Reference: "https://spdx.org/licenses/GPL-2.0-with-GCC-exception.html",
		},
		{
			ID:        "GPL-2.0-with-autoconf-exception",
			Reference: "https://spdx.org/licenses/GPL-2.0-with-autoconf-exception.html",
		},
		{
			ID:        "GPL-2.0-with-bison-exception",
			Reference: "https://spdx.org/licenses/GPL-2.0-with-bison-exception.html",
		},
		{
			ID:        "GPL-2.0-with-classpath-exception",
			Reference: "https://spdx.org/licenses/GPL-2.0-with-classpath-exception.html",
		},
		{
			ID:        "GPL-2.0-with-font-exception",
			Reference: "https://spdx.org/licenses/GPL-2.0-with-font-exception.html",
		},
		{
			ID:        "GPL-3.0",
			Reference: "https://spdx.org/licenses/GPL-3.0.html",
		},
		{
			ID:        "GPL-3.0+",
			Reference: "https://spdx.org/licenses/GPL-3.0+.html",
		},
		{
			ID:        "GPL-3.0-only",
			Reference: "https://spdx.org/licenses/GPL-3.0-only.html",
		},
		{
			ID:        "GPL-3.0-or-later",
			Reference: "https://spdx.org/licenses/GPL-3.0-or-later.html",
		},
		{
			ID:        "GPL-3.0-with-GCC-exception",
			Reference: "https://spdx.org/licenses/GPL-3.0-with-GCC-exception.html",
		},
		{
			ID:        "GPL-3.0-with-autoconf-exception",
			Reference: "https://spdx.org/licenses/GPL-3.0-with-autoconf-exception.html",
		},
		{
			ID:        "Giftware",
			Reference: "https://spdx.org/licenses/Giftware.html",
		},
		{
			ID:        "Glide",
			Reference: "https://spdx.org/licenses/Glide.html",
		},
		{
			ID:        "Glulxe",
			Reference: "https://spdx.org/licenses/Glulxe.html",
		},
		{
			ID:        "HPND",
			Reference: "https://spdx.org/licenses/HPND.html",
		},
		{
			ID:        "HPND-sell-variant",
			Reference: "https://spdx.org/licenses/HPND-sell-variant.html",
		},
		{
			ID:        "HTMLTIDY",
			Reference: "https://spdx.org/licenses/HTMLTIDY.html",
		},
		{
			ID:        "HaskellReport",
			Reference: "https://spdx.org/licenses/HaskellReport.html",
		},
		{
			ID:        "Hippocratic-2.1",
			Reference: "https://spdx.org/licenses/Hippocratic-2.1.html",
		},
		{
			ID:        "IBM-pibs",
			Reference: "https://spdx.org/licenses/IBM-pibs.html",
		},
		{
			ID:        "ICU",
			Reference: "https://spdx.org/licenses/ICU.html",
		},
		{
			ID:        "IJG",
			Reference: "https://spdx.org/licenses/IJG.html",
		},
		{
			ID:        "IPA",
			Reference: "https://spdx.org/licenses/IPA.html",
		},
		{
			ID:        "IPL-1.0",
			Reference: "https://spdx.org/licenses/IPL-1.0.html",
		},
		{
			ID:        "ISC",
			Reference: "https://spdx.org/licenses/ISC.html",
		},
		{
			ID:        "ImageMagick",
			Reference: "https://spdx.org/licenses/ImageMagick.html",
		},
		{
			ID:        "Imlib2",
			Reference: "https://spdx.org/licenses/Imlib2.html",
		},
		{
			ID:        "Info-ZIP",
			Reference: "https://spdx.org/licenses/Info-ZIP.html",
		},
		{
			ID:        "Intel",
			Reference: "https://spdx.org/licenses/Intel.html",
		},
		{
			ID:        "Intel-ACPI",
			Reference: "https://spdx.org/licenses/Intel-ACPI.html",
		},
		{
			ID:        "Interbase-1.0",
			Reference: "https://spdx.org/licenses/Interbase-1.0.html",
		},
		{
			ID:        "JPNIC",
			Reference: "https://spdx.org/licenses/JPNIC.html",
		},
		{
			ID:        "JSON",
			Reference: "https://spdx.org/licenses/JSON.html",
		},
		{
			ID:        "JasPer-2.0",
			Reference: "https://spdx.org/licenses/JasPer-2.0.html",
		},
		{
			ID:        "LAL-1.2",
			Reference: "https://spdx.org/licenses/LAL-1.2.html",
		},
		{
			ID:        "LAL-1.3",
			Reference: "https://spdx.org/licenses/LAL-1.3.html",
		},
		{
			ID:        "LGPL-2.0",
			Reference: "https://spdx.org/licenses/LGPL-2.0.html",
		},
		{
			ID:        "LGPL-2.0+",
			Reference: "https://spdx.org/licenses/LGPL-2.0+.html",
		},
		{
			ID:        "LGPL-2.0-only",
			Reference: "https://spdx.org/licenses/LGPL-2.0-only.html",
		},
		{
			ID:        "LGPL-2.0-or-later",
			Reference: "https://spdx.org/licenses/LGPL-2.0-or-later.html",
		},
		{
			ID:        "LGPL-2.1",
			Reference: "https://spdx.org/licenses/LGPL-2.1.html",
		},
		{
			ID:        "LGPL-2.1+",
			Reference: "https://spdx.org/licenses/LGPL-2.1+.html",
		},
		{
			ID:        "LGPL-2.1-only",
			Reference: "https://spdx.org/licenses/LGPL-2.1-only.html",
		},
		{
			ID:        "LGPL-2.1-or-later",
			Reference: "https://spdx.org/licenses/LGPL-2.1-or-later.html",
		},
		{
			ID:        "LGPL-3.0",
			Reference: "https://spdx.org/licenses/LGPL-3.0.html",
		},
		{
			ID:        "LGPL-3.0+",
			Reference: "https://spdx.org/licenses/LGPL-3.0+.html",
		},
		{
			ID:        "LGPL-3.0-only",
			Reference: "https://spdx.org/licenses/LGPL-3.0-only.html",
		},
		{
			ID:        "LGPL-3.0-or-later",
			Reference: "https://spdx.org/licenses/LGPL-3.0-or-later.html",
		},
		{
			ID:        "LGPLLR",
			Reference: "https://spdx.org/licenses/LGPLLR.html",
		},
		{
			ID:        "LPL-1.0",
			Reference: "https://spdx.org/licenses/LPL-1.0.html",
		},
		{
			ID:        "LPL-1.02",
			Reference: "https://spdx.org/licenses/LPL-1.02.html",
		},
		{
			ID:        "LPPL-1.0",
			Reference: "https://spdx.org/licenses/LPPL-1.0.html",
		},
		{
			ID:        "LPPL-1.1",
			Reference: "https://spdx.org/licenses/LPPL-1.1.html",
		},
		{
			ID:        "LPPL-1.2",
			Reference: "https://spdx.org/licenses/LPPL-1.2.html",
		},
		{
			ID:        "LPPL-1.3a",
			Reference: "https://spdx.org/licenses/LPPL-1.3a.html",
		},
		{
			ID:        "LPPL-1.3c",
			Reference: "https://spdx.org/licenses/LPPL-1.3c.html",
		},
		{
			ID:        "Latex2e",
			Reference: "https://spdx.org/licenses/Latex2e.html",
		},
		{
			ID:        "Leptonica",
			Reference: "https://spdx.org/licenses/Leptonica.html",
		},
		{
			ID:        "LiLiQ-P-1.1",
			Reference: "https://spdx.org/licenses/LiLiQ-P-1.1.html",
		},
		{
			ID:        "LiLiQ-R-1.1",
			Reference: "https://spdx.org/licenses/LiLiQ-R-1.1.html",
		},
		{
			ID:        "LiLiQ-Rplus-1.1",
			Reference: "https://spdx.org/licenses/LiLiQ-Rplus-1.1.html",
		},
		{
			ID:        "Libpng",
			Reference: "https://spdx.org/licenses/Libpng.html",
		},
		{
			ID:        "Linux-OpenIB",
			Reference: "https://spdx.org/licenses/Linux-OpenIB.html",
		},
		{
			ID:        "MIT",
			Reference: "https://spdx.org/licenses/MIT.html",
		},
		{
			ID:        "MIT-0",
			Reference: "https://spdx.org/licenses/MIT-0.html",
		},
		{
			ID:        "MIT-CMU",
			Reference: "https://spdx.org/licenses/MIT-CMU.html",
		},
		{
			ID:        "MIT-Modern-Variant",
			Reference: "https://spdx.org/licenses/MIT-Modern-Variant.html",
		},
		{
			ID:        "MIT-advertising",
			Reference: "https://spdx.org/licenses/MIT-advertising.html",
		},
		{
			ID:        "MIT-enna",
			Reference: "https://spdx.org/licenses/MIT-enna.html",
		},
		{
			ID:        "MIT-feh",
			Reference: "https://spdx.org/licenses/MIT-feh.html",
		},
		{
			ID:        "MIT-open-group",
			Reference: "https://spdx.org/licenses/MIT-open-group.html",
		},
		{
			ID:        "MITNFA",
			Reference: "https://spdx.org/licenses/MITNFA.html",
		},
		{
			ID:        "MPL-1.0",
			Reference: "https://spdx.org/licenses/MPL-1.0.html",
		},
		{
			ID:        "MPL-1.1",
			Reference: "https://spdx.org/licenses/MPL-1.1.html",
		},
		{
			ID:        "MPL-2.0",
			Reference: "https://spdx.org/licenses/MPL-2.0.html",
		},
		{
			ID:        "MPL-2.0-no-copyleft-exception",
			Reference: "https://spdx.org/licenses/MPL-2.0-no-copyleft-exception.html",
		},
		{
			ID:        "MS-PL",
			Reference: "https://spdx.org/licenses/MS-PL.html",
		},
		{
			ID:        "MS-RL",
			Reference: "https://spdx.org/licenses/MS-RL.html",
		},
		{
			ID:        "MTLL",
			Reference: "https://spdx.org/licenses/MTLL.html",
		},
		{
			ID:        "MakeIndex",
			Reference: "https://spdx.org/licenses/MakeIndex.html",
		},
		{
			ID:        "MirOS",
			Reference: "https://spdx.org/licenses/MirOS.html",
		},
		{
			ID:        "Motosoto",
			Reference: "https://spdx.org/licenses/Motosoto.html",
		},
		{
			ID:        "MulanPSL-1.0",
			Reference: "https://spdx.org/licenses/MulanPSL-1.0.html",
		},
		{
			ID:        "MulanPSL-2.0",
			Reference: "https://spdx.org/licenses/MulanPSL-2.0.html",
		},
		{
			ID:        "Multics",
			Reference: "https://spdx.org/licenses/Multics.html",
		},
		{
			ID:        "Mup",
			Reference: "https://spdx.org/licenses/Mup.html",
		},
		{
			ID:        "NAIST-2003",
			Reference: "https://spdx.org/licenses/NAIST-2003.html",
		},
		{
			ID:        "NASA-1.3",
			Reference: "https://spdx.org/licenses/NASA-1.3.html",
		},
		{
			ID:        "NBPL-1.0",
			Reference: "https://spdx.org/licenses/NBPL-1.0.html",
		},
		{
			ID:        "NCGL-UK-2.0",
			Reference: "https://spdx.org/licenses/NCGL-UK-2.0.html",
		},
		{
			ID:        "NCSA",
			Reference: "https://spdx.org/licenses/NCSA.html",
		},
		{
			ID:        "NGPL",
			Reference: "https://spdx.org/licenses/NGPL.html",
		},
		{
			ID:        "NIST-PD",
			Reference: "https://spdx.org/licenses/NIST-PD.html",
		},
		{
			ID:        "NIST-PD-fallback",
			Reference: "https://spdx.org/licenses/NIST-PD-fallback.html",
		},
		{
			ID:        "NLOD-1.0",
			Reference: "https://spdx.org/licenses/NLOD-1.0.html",
		},
		{
			ID:        "NLPL",
			Reference: "https://spdx.org/licenses/NLPL.html",
		},
		{
			ID:        "NOSL",
			Reference: "https://spdx.org/licenses/NOSL.html",
		},
		{
			ID:        "NPL-1.0",
			Reference: "https://spdx.org/licenses/NPL-1.0.html",
		},
		{
			ID:        "NPL-1.1",
			Reference: "https://spdx.org/licenses/NPL-1.1.html",
		},
		{
			ID:        "NPOSL-3.0",
			Reference: "https://spdx.org/licenses/NPOSL-3.0.html",
		},
		{
			ID:        "NRL",
			Reference: "https://spdx.org/licenses/NRL.html",
		},
		{
			ID:        "NTP",
			Reference: "https://spdx.org/licenses/NTP.html",
		},
		{
			ID:        "NTP-0",
			Reference: "https://spdx.org/licenses/NTP-0.html",
		},
		{
			ID:        "Naumen",
			Reference: "https://spdx.org/licenses/Naumen.html",
		},
		{
			ID:        "Net-SNMP",
			Reference: "https://spdx.org/licenses/Net-SNMP.html",
		},
		{
			ID:        "NetCDF",
			Reference: "https://spdx.org/licenses/NetCDF.html",
		},
		{
			ID:        "Newsletr",
			Reference: "https://spdx.org/licenses/Newsletr.html",
		},
		{
			ID:        "Nokia",
			Reference: "https://spdx.org/licenses/Nokia.html",
		},
		{
			ID:        "Noweb",
			Reference: "https://spdx.org/licenses/Noweb.html",
		},
		{
			ID:        "Nunit",
			Reference: "https://spdx.org/licenses/Nunit.html",
		},
		{
			ID:        "O-UDA-1.0",
			Reference: "https://spdx.org/licenses/O-UDA-1.0.html",
		},
		{
			ID:        "OCCT-PL",
			Reference: "https://spdx.org/licenses/OCCT-PL.html",
		},
		{
			ID:        "OCLC-2.0",
			Reference: "https://spdx.org/licenses/OCLC-2.0.html",
		},
		{
			ID:        "ODC-By-1.0",
			Reference: "https://spdx.org/licenses/ODC-By-1.0.html",
		},
		{
			ID:        "ODbL-1.0",
			Reference: "https://spdx.org/licenses/ODbL-1.0.html",
		},
		{
			ID:        "OFL-1.0",
			Reference: "https://spdx.org/licenses/OFL-1.0.html",
		},
		{
			ID:        "OFL-1.0-RFN",
			Reference: "https://spdx.org/licenses/OFL-1.0-RFN.html",
		},
		{
			ID:        "OFL-1.0-no-RFN",
			Reference: "https://spdx.org/licenses/OFL-1.0-no-RFN.html",
		},
		{
			ID:        "OFL-1.1",
			Reference: "https://spdx.org/licenses/OFL-1.1.html",
		},
		{
			ID:        "OFL-1.1-RFN",
			Reference: "https://spdx.org/licenses/OFL-1.1-RFN.html",
		},
		{
			ID:        "OFL-1.1-no-RFN",
			Reference: "https://spdx.org/licenses/OFL-1.1-no-RFN.html",
		},
		{
			ID:        "OGC-1.0",
			Reference: "https://spdx.org/licenses/OGC-1.0.html",
		},
		{
			ID:        "OGDL-Taiwan-1.0",
			Reference: "https://spdx.org/licenses/OGDL-Taiwan-1.0.html",
		},
		{
			ID:        "OGL-Canada-2.0",
			Reference: "https://spdx.org/licenses/OGL-Canada-2.0.html",
		},
		{
			ID:        "OGL-UK-1.0",
			Reference: "https://spdx.org/licenses/OGL-UK-1.0.html",
		},
		{
			ID:        "OGL-UK-2.0",
			Reference: "https://spdx.org/licenses/OGL-UK-2.0.html",
		},
		{
			ID:        "OGL-UK-3.0",
			Reference: "https://spdx.org/licenses/OGL-UK-3.0.html",
		},
		{
			ID:        "OGTSL",
			Reference: "https://spdx.org/licenses/OGTSL.html",
		},
		{
			ID:        "OLDAP-1.1",
			Reference: "https://spdx.org/licenses/OLDAP-1.1.html",
		},
		{
			ID:        "OLDAP-1.2",
			Reference: "https://spdx.org/licenses/OLDAP-1.2.html",
		},
		{
			ID:        "OLDAP-1.3",
			Reference: "https://spdx.org/licenses/OLDAP-1.3.html",
		},
		{
			ID:        "OLDAP-1.4",
			Reference: "https://spdx.org/licenses/OLDAP-1.4.html",
		},
		{
			ID:        "OLDAP-2.0",
			Reference: "https://spdx.org/licenses/OLDAP-2.0.html",
		},
		{
			ID:        "OLDAP-2.0.1",
			Reference: "https://spdx.org/licenses/OLDAP-2.0.1.html",
		},
		{
			ID:        "OLDAP-2.1",
			Reference: "https://spdx.org/licenses/OLDAP-2.1.html",
		},
		{
			ID:        "OLDAP-2.2",
			Reference: "https://spdx.org/licenses/OLDAP-2.2.html",
		},
		{
			ID:        "OLDAP-2.2.1",
			Reference: "https://spdx.org/licenses/OLDAP-2.2.1.html",
		},
		{
			ID:        "OLDAP-2.2.2",
			Reference: "https://spdx.org/licenses/OLDAP-2.2.2.html",
		},
		{
			ID:        "OLDAP-2.3",
			Reference: "https://spdx.org/licenses/OLDAP-2.3.html",
		},
		{
			ID:        "OLDAP-2.4",
			Reference: "https://spdx.org/licenses/OLDAP-2.4.html",
		},
		{
			ID:        "OLDAP-2.5",
			Reference: "https://spdx.org/licenses/OLDAP-2.5.html",
		},
		{
			ID:        "OLDAP-2.6",
			Reference: "https://spdx.org/licenses/OLDAP-2.6.html",
		},
		{
			ID:        "OLDAP-2.7",
			Reference: "https://spdx.org/licenses/OLDAP-2.7.html",
		},
		{
			ID:        "OLDAP-2.8",
			Reference: "https://spdx.org/licenses/OLDAP-2.8.html",
		},
		{
			ID:        "OML",
			Reference: "https://spdx.org/licenses/OML.html",
		},
		{
			ID:        "OPL-1.0",
			Reference: "https://spdx.org/licenses/OPL-1.0.html",
		},
		{
			ID:        "OPUBL-1.0",
			Reference: "https://spdx.org/licenses/OPUBL-1.0.html",
		},
		{
			ID:        "OSET-PL-2.1",
			Reference: "https://spdx.org/licenses/OSET-PL-2.1.html",
		},
		{
			ID:        "OSL-1.0",
			Reference: "https://spdx.org/licenses/OSL-1.0.html",
		},
		{
			ID:        "OSL-1.1",
			Reference: "https://spdx.org/licenses/OSL-1.1.html",
		},
		{
			ID:        "OSL-2.0",
			Reference: "https://spdx.org/licenses/OSL-2.0.html",
		},
		{
			ID:        "OSL-2.1",
			Reference: "https://spdx.org/licenses/OSL-2.1.html",
		},
		{
			ID:        "OSL-3.0",
			Reference: "https://spdx.org/licenses/OSL-3.0.html",
		},
		{
			ID:        "OpenSSL",
			Reference: "https://spdx.org/licenses/OpenSSL.html",
		},
		{
			ID:        "PDDL-1.0",
			Reference: "https://spdx.org/licenses/PDDL-1.0.html",
		},
		{
			ID:        "PHP-3.0",
			Reference: "https://spdx.org/licenses/PHP-3.0.html",
		},
		{
			ID:        "PHP-3.01",
			Reference: "https://spdx.org/licenses/PHP-3.01.html",
		},
		{
			ID:        "PSF-2.0",
			Reference: "https://spdx.org/licenses/PSF-2.0.html",
		},
		{
			ID:        "Parity-6.0.0",
			Reference: "https://spdx.org/licenses/Parity-6.0.0.html",
		},
		{
			ID:        "Parity-7.0.0",
			Reference: "https://spdx.org/licenses/Parity-7.0.0.html",
		},
		{
			ID:        "Plexus",
			Reference: "https://spdx.org/licenses/Plexus.html",
		},
		{
			ID:        "PolyForm-Noncommercial-1.0.0",
			Reference: "https://spdx.org/licenses/PolyForm-Noncommercial-1.0.0.html",
		},
		{
			ID:        "PolyForm-Small-Business-1.0.0",
			Reference: "https://spdx.org/licenses/PolyForm-Small-Business-1.0.0.html",
		},
		{
			ID:        "PostgreSQL",
			Reference: "https://spdx.org/licenses/PostgreSQL.html",
		},
		{
			ID:        "Python-2.0",
			Reference: "https://spdx.org/licenses/Python-2.0.html",
		},
		{
			ID:        "QPL-1.0",
			Reference: "https://spdx.org/licenses/QPL-1.0.html",
		},
		{
			ID:        "Qhull",
			Reference: "https://spdx.org/licenses/Qhull.html",
		},
		{
			ID:        "RHeCos-1.1",
			Reference: "https://spdx.org/licenses/RHeCos-1.1.html",
		},
		{
			ID:        "RPL-1.1",
			Reference: "https://spdx.org/licenses/RPL-1.1.html",
		},
		{
			ID:        "RPL-1.5",
			Reference: "https://spdx.org/licenses/RPL-1.5.html",
		},
		{
			ID:        "RPSL-1.0",
			Reference: "https://spdx.org/licenses/RPSL-1.0.html",
		},
		{
			ID:        "RSA-MD",
			Reference: "https://spdx.org/licenses/RSA-MD.html",
		},
		{
			ID:        "RSCPL",
			Reference: "https://spdx.org/licenses/RSCPL.html",
		},
		{
			ID:        "Rdisc",
			Reference: "https://spdx.org/licenses/Rdisc.html",
		},
		{
			ID:        "Ruby",
			Reference: "https://spdx.org/licenses/Ruby.html",
		},
		{
			ID:        "SAX-PD",
			Reference: "https://spdx.org/licenses/SAX-PD.html",
		},
		{
			ID:        "SCEA",
			Reference: "https://spdx.org/licenses/SCEA.html",
		},
		{
			ID:        "SGI-B-1.0",
			Reference: "https://spdx.org/licenses/SGI-B-1.0.html",
		},
		{
			ID:        "SGI-B-1.1",
			Reference: "https://spdx.org/licenses/SGI-B-1.1.html",
		},
		{
			ID:        "SGI-B-2.0",
			Reference: "https://spdx.org/licenses/SGI-B-2.0.html",
		},
		{
			ID:        "SHL-0.5",
			Reference: "https://spdx.org/licenses/SHL-0.5.html",
		},
		{
			ID:        "SHL-0.51",
			Reference: "https://spdx.org/licenses/SHL-0.51.html",
		},
		{
			ID:        "SISSL",
			Reference: "https://spdx.org/licenses/SISSL.html",
		},
		{
			ID:        "SISSL-1.2",
			Reference: "https://spdx.org/licenses/SISSL-1.2.html",
		},
		{
			ID:        "SMLNJ",
			Reference: "https://spdx.org/licenses/SMLNJ.html",
		},
		{
			ID:        "SMPPL",
			Reference: "https://spdx.org/licenses/SMPPL.html",
		},
		{
			ID:        "SNIA",
			Reference: "https://spdx.org/licenses/SNIA.html",
		},
		{
			ID:        "SPL-1.0",
			Reference: "https://spdx.org/licenses/SPL-1.0.html",
		},
		{
			ID:        "SSH-OpenSSH",
			Reference: "https://spdx.org/licenses/SSH-OpenSSH.html",
		},
		{
			ID:        "SSH-short",
			Reference: "https://spdx.org/licenses/SSH-short.html",
		},
		{
			ID:        "SSPL-1.0",
			Reference: "https://spdx.org/licenses/SSPL-1.0.html",
		},
		{
			ID:        "SWL",
			Reference: "https://spdx.org/licenses/SWL.html",
		},
		{
			ID:        "Saxpath",
			Reference: "https://spdx.org/licenses/Saxpath.html",
		},
		{
			ID:        "Sendmail",
			Reference: "https://spdx.org/licenses/Sendmail.html",
		},
		{
			ID:        "Sendmail-8.23",
			Reference: "https://spdx.org/licenses/Sendmail-8.23.html",
		},
		{
			ID:        "SimPL-2.0",
			Reference: "https://spdx.org/licenses/SimPL-2.0.html",
		},
		{
			ID:        "Sleepycat",
			Reference: "https://spdx.org/licenses/Sleepycat.html",
		},
		{
			ID:        "Spencer-86",
			Reference: "https://spdx.org/licenses/Spencer-86.html",
		},
		{
			ID:        "Spencer-94",
			Reference: "https://spdx.org/licenses/Spencer-94.html",
		},
		{
			ID:        "Spencer-99",
			Reference: "https://spdx.org/licenses/Spencer-99.html",
		},
		{
			ID:        "StandardML-NJ",
			Reference: "https://spdx.org/licenses/StandardML-NJ.html",
		},
		{
			ID:        "SugarCRM-1.1.3",
			Reference: "https://spdx.org/licenses/SugarCRM-1.1.3.html",
		},
		{
			ID:        "TAPR-OHL-1.0",
			Reference: "https://spdx.org/licenses/TAPR-OHL-1.0.html",
		},
		{
			ID:        "TCL",
			Reference: "https://spdx.org/licenses/TCL.html",
		},
		{
			ID:        "TCP-wrappers",
			Reference: "https://spdx.org/licenses/TCP-wrappers.html",
		},
		{
			ID:        "TMate",
			Reference: "https://spdx.org/licenses/TMate.html",
		},
		{
			ID:        "TORQUE-1.1",
			Reference: "https://spdx.org/licenses/TORQUE-1.1.html",
		},
		{
			ID:        "TOSL",
			Reference: "https://spdx.org/licenses/TOSL.html",
		},
		{
			ID:        "TU-Berlin-1.0",
			Reference: "https://spdx.org/licenses/TU-Berlin-1.0.html",
		},
		{
			ID:        "TU-Berlin-2.0",
			Reference: "https://spdx.org/licenses/TU-Berlin-2.0.html",
		},
		{
			ID:        "UCL-1.0",
			Reference: "https://spdx.org/licenses/UCL-1.0.html",
		},
		{
			ID:        "UPL-1.0",
			Reference: "https://spdx.org/licenses/UPL-1.0.html",
		},
		{
			ID:        "Unicode-DFS-2015",
			Reference: "https://spdx.org/licenses/Unicode-DFS-2015.html",
		},
		{
			ID:        "Unicode-DFS-2016",
			Reference: "https://spdx.org/licenses/Unicode-DFS-2016.html",
		},
		{
			ID:        "Unicode-TOU",
			Reference: "https://spdx.org/licenses/Unicode-TOU.html",
		},
		{
			ID:        "Unlicense",
			Reference: "https://spdx.org/licenses/Unlicense.html",
		},
		{
			ID:        "VOSTROM",
			Reference: "https://spdx.org/licenses/VOSTROM.html",
		},
		{
			ID:        "VSL-1.0",
			Reference: "https://spdx.org/licenses/VSL-1.0.html",
		},
		{
			ID:        "Vim",
			Reference: "https://spdx.org/licenses/Vim.html",
		},
		{
			ID:        "W3C",
			Reference: "https://spdx.org/licenses/W3C.html",
		},
		{
			ID:        "W3C-19980720",
			Reference: "https://spdx.org/licenses/W3C-19980720.html",
		},
		{
			ID:        "W3C-20150513",
			Reference: "https://spdx.org/licenses/W3C-20150513.html",
		},
		{
			ID:        "WTFPL",
			Reference: "https://spdx.org/licenses/WTFPL.html",
		},
		{
			ID:        "Watcom-1.0",
			Reference: "https://spdx.org/licenses/Watcom-1.0.html",
		},
		{
			ID:        "Wsuipa",
			Reference: "https://spdx.org/licenses/Wsuipa.html",
		},
		{
			ID:        "X11",
			Reference: "https://spdx.org/licenses/X11.html",
		},
		{
			ID:        "XFree86-1.1",
			Reference: "https://spdx.org/licenses/XFree86-1.1.html",
		},
		{
			ID:        "XSkat",
			Reference: "https://spdx.org/licenses/XSkat.html",
		},
		{
			ID:        "Xerox",
			Reference: "https://spdx.org/licenses/Xerox.html",
		},
		{
			ID:        "Xnet",
			Reference: "https://spdx.org/licenses/Xnet.html",
		},
		{
			ID:        "YPL-1.0",
			Reference: "https://spdx.org/licenses/YPL-1.0.html",
		},
		{
			ID:        "YPL-1.1",
			Reference: "https://spdx.org/licenses/YPL-1.1.html",
		},
		{
			ID:        "ZPL-1.1",
			Reference: "https://spdx.org/licenses/ZPL-1.1.html",
		},
		{
			ID:        "ZPL-2.0",
			Reference: "https://spdx.org/licenses/ZPL-2.0.html",
		},
		{
			ID:        "ZPL-2.1",
			Reference: "https://spdx.org/licenses/ZPL-2.1.html",
		},
		{
			ID:        "Zed",
			Reference: "https://spdx.org/licenses/Zed.html",
		},
		{
			ID:        "Zend-2.0",
			Reference: "https://spdx.org/licenses/Zend-2.0.html",
		},
		{
			ID:        "Zimbra-1.3",
			Reference: "https://spdx.org/licenses/Zimbra-1.3.html",
		},
		{
			ID:        "Zimbra-1.4",
			Reference: "https://spdx.org/licenses/Zimbra-1.4.html",
		},
		{
			ID:        "Zlib",
			Reference: "https://spdx.org/licenses/Zlib.html",
		},
		{
			ID:        "blessing",
			Reference: "https://spdx.org/licenses/blessing.html",
		},
		{
			ID:        "bzip2-1.0.5",
			Reference: "https://spdx.org/licenses/bzip2-1.0.5.html",
		},
		{
			ID:        "bzip2-1.0.6",
			Reference: "https://spdx.org/licenses/bzip2-1.0.6.html",
		},
		{
			ID:        "copyleft-next-0.3.0",
			Reference: "https://spdx.org/licenses/copyleft-next-0.3.0.html",
		},
		{
			ID:        "copyleft-next-0.3.1",
			Reference: "https://spdx.org/licenses/copyleft-next-0.3.1.html",
		},
		{
			ID:        "curl",
			Reference: "https://spdx.org/licenses/curl.html",
		},
		{
			ID:        "diffmark",
			Reference: "https://spdx.org/licenses/diffmark.html",
		},
		{
			ID:        "dvipdfm",
			Reference: "https://spdx.org/licenses/dvipdfm.html",
		},
		{
			ID:        "eCos-2.0",
			Reference: "https://spdx.org/licenses/eCos-2.0.html",
		},
		{
			ID:        "eGenix",
			Reference: "https://spdx.org/licenses/eGenix.html",
		},
		{
			ID:        "etalab-2.0",
			Reference: "https://spdx.org/licenses/etalab-2.0.html",
		},
		{
			ID:        "gSOAP-1.3b",
			Reference: "https://spdx.org/licenses/gSOAP-1.3b.html",
		},
		{
			ID:        "gnuplot",
			Reference: "https://spdx.org/licenses/gnuplot.html",
		},
		{
			ID:        "iMatix",
			Reference: "https://spdx.org/licenses/iMatix.html",
		},
		{
			ID:        "libpng-2.0",
			Reference: "https://spdx.org/licenses/libpng-2.0.html",
		},
		{
			ID:        "libselinux-1.0",
			Reference: "https://spdx.org/licenses/libselinux-1.0.html",
		},
		{
			ID:        "libtiff",
			Reference: "https://spdx.org/licenses/libtiff.html",
		},
		{
			ID:        "mpich2",
			Reference: "https://spdx.org/licenses/mpich2.html",
		},
		{
			ID:        "psfrag",
			Reference: "https://spdx.org/licenses/psfrag.html",
		},
		{
			ID:        "psutils",
			Reference: "https://spdx.org/licenses/psutils.html",
		},
		{
			ID:        "wxWindows",
			Reference: "https://spdx.org/licenses/wxWindows.html",
		},
		{
			ID:        "xinetd",
			Reference: "https://spdx.org/licenses/xinetd.html",
		},
		{
			ID:        "xpp",
			Reference: "https://spdx.org/licenses/xpp.html",
		},
		{
			ID:        "zlib-acknowledgement",
			Reference: "https://spdx.org/licenses/zlib-acknowledgement.html",
		},
	}
}
