tasks:
  - init: |
      mkdir -p "$HOME/.local/bin"
      export $PATH="$HOME/.local/bin:$PATH"
      wget -O "$HOME/.local/bin/cyclonedx" https://github.com/CycloneDX/cyclonedx-cli/releases/download/v0.22.0/cyclonedx-linux-x64
      echo "ae39404a9dc8b2e7be0a9559781ee9fe3492201d2629de139d702fd4535ffdd6 $HOME/.local/bin/cyclonedx" | sha256sum -c
      chmod +x "$HOME/.local/bin/cyclonedx"
      make build

vscode:
  extensions:
    - golang.Go
    - premparihar.gotestexplorer