linters:
  enable:
    - asciicheck
    - exhaustive
    - gochecknoinits
    - goconst
    - gofmt
    - gosec
    - predeclared
    - unconvert
    - unparam
    - wastedassign

linters-settings:
  goconst:
    ignore-tests: true
