version: "2"
linters:
  enable:
  - asciicheck
  - exhaustive
  - gochecknoinits
  - goconst
  - gosec
  - predeclared
  - unconvert
  - unparam
  - wastedassign
  settings:
    gosec:
      config:
        global:
          nosec: true
  exclusions:
    generated: lax
    presets:
    - comments
    - common-false-positives
    - legacy
    - std-error-handling
    rules:
    - linters:
      - goconst
      path: (.+)_test\.go
    paths:
    - third_party$
    - builtin$
    - examples$
formatters:
  enable:
  - gofmt
  exclusions:
    generated: lax
    paths:
    - third_party$
    - builtin$
    - examples$
