version: 2

project_name: cyclonedx-gomod

before:
  hooks:
  - go mod tidy
  # Prebuild a binary that'll be used to generate SBOMs later
  - sh -c "VERSION={{ .Version }} make build"

gomod:
  proxy: true

builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - windows
  - darwin
  goarch:
  - amd64
  - arm64
  flags: -trimpath
  ldflags: -s -w
  main: ./cmd/cyclonedx-gomod
  mod_timestamp: "{{ .CommitTimestamp }}"

sboms:
- documents:
  - "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.bom.json"
  artifacts: binary
  cmd: "../bin/cyclonedx-gomod"
  args: [ "app", "-main", "./cmd/cyclonedx-gomod", "-licenses", "-packages", "-std", "-json", "-output", "$document", "../" ]
  env:
  - GOARCH={{ .Arch }}
  - GOOS={{ .Os }}

signs:
  - cmd: cosign
    certificate: '${artifact}.pem'
    args:
      - sign-blob
      - '--use-signing-config=false'
      - '--new-bundle-format=false'
      - '--output-certificate=${certificate}'
      - '--output-signature=${signature}'
      - '${artifact}'
      - '--yes'
    artifacts: checksum
    output: true

dockers_v2:
- dockerfile: Dockerfile.goreleaser
  images:
  - "cyclonedx/{{ .ProjectName }}"
  platforms:
  - linux/amd64
  - linux/arm64
  sbom: false
  tags:
  - "latest"
  - "{{ .Tag }}"
  - "v{{ .Major }}"
  - "v{{ .Major }}.{{ .Minor }}"
  labels:
    org.opencontainers.image.title: "{{ .ProjectName }}"
    org.opencontainers.image.version: "{{ .Tag }}"
    org.opencontainers.image.revision: "{{ .FullCommit }}"
    org.opencontainers.image.created: "{{ .Date }}"
    org.opencontainers.image.vendor: "CycloneDX"
    org.opencontainers.image.url: "https://cyclonedx.org"
    org.opencontainers.image.source: "{{ .GitURL }}"

docker_signs:
  - cmd: cosign
    artifacts: all
    output: true
    args:
    - 'sign'
    - '${artifact}'
    - '--yes'

archives:
- format_overrides:
  - goos: windows
    formats: [ zip ]

release:
  prerelease: auto
  extra_files:
  - glob: ./*.bom.json

milestones:
- name_template: "{{ .Tag }}"
  close: true

changelog:
  use: github
  sort: asc
  groups:
  - title: Features
    regexp: "^.*feat[(\\w)]*:+.*$"
    order: 0
  - title: Fixes
    regexp: "^.*fix[(\\w)]*:+.*$"
    order: 1
  - title: Building and Packaging
    regexp: "^.*build[(\\w)]*:+.*$"
    order: 2
  - title: Documentation
    regexp: "^.*docs[(\\w)]*:+.*$"
    order: 3
  - title: Others
    order: 999
  filters:
    exclude:
    - '^test:'
    - '^Merge '
