name: GoReleaser CI

on:
  workflow_dispatch: { }

permissions: { }

jobs:
  goreleaser-ci:
    name: Test Release
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # tag=v6.0.2
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # tag=v6.2.0
      with:
        go-version: "1.25"
        check-latest: true
    - name: Set up QEMU
      uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # tag=v4.0.0
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # tag=v7.2.3
      with:
        version: latest
        args: release --skip publish,sign --snapshot